import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Meteors } from "@/components/ui/meteors";
import { MultiStepLoaderDemo } from "@/components/Loader";
import { GoogleGeminiEffectDemo } from "@/components/Gemini";
import { ThreeDCardDemo } from "@/components/card3d";
import { GlobeDemo } from "@/components/globe3d";
import { CanvasRevealEffectDemo } from "@/components/canvasr";
import { HeroHighlightDemo } from "@/components/heroH";
import { VortexDemo } from "@/components/vortex";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {/* <MultiStepLoaderDemo /> */}
        <GoogleGeminiEffectDemo />
        <Meteors />
        {children}
        {/* <ThreeDCardDemo /> */}
        <CanvasRevealEffectDemo />
        <HeroHighlightDemo />
        <VortexDemo />
        <GlobeDemo />
      </body>
    </html>
  );
}
